#############################################################################
# Makefile for building: Pokedex
# Generated by qmake (2.01a) (Qt 4.6.2) on: Sun Nov 14 09:53:12 2010
# Project:  Pokedex.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile Pokedex.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)   -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = equip.cpp \
		evolution.cpp \
		level.cpp \
		main.cpp \
		mainwindow.cpp \
		pokedexParser.cpp \
		pokedexwindow.cpp \
		pokemon.cpp \
		tm_hm.cpp moc_mainwindow.cpp \
		moc_pokedexwindow.cpp
OBJECTS       = equip.o \
		evolution.o \
		level.o \
		main.o \
		mainwindow.o \
		pokedexParser.o \
		pokedexwindow.o \
		pokemon.o \
		tm_hm.o \
		moc_mainwindow.o \
		moc_pokedexwindow.o
DIST          = /usr/lib/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		Pokedex.pro
QMAKE_TARGET  = Pokedex
DESTDIR       = 
TARGET        = Pokedex

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Pokedex.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile Pokedex.pro
/usr/lib/qt4/mkspecs/common/g++-multilib.conf:
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/release.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Pokedex.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Pokedex1.0.0 || $(MKDIR) .tmp/Pokedex1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Pokedex1.0.0/ && $(COPY_FILE) --parents equip.h evolution.h level.h mainwindow.h pokedexParser.h pokedexwindow.h pokemon.h special.h tm_hm.h .tmp/Pokedex1.0.0/ && $(COPY_FILE) --parents equip.cpp evolution.cpp level.cpp main.cpp mainwindow.cpp pokedexParser.cpp pokedexwindow.cpp pokemon.cpp tm_hm.cpp .tmp/Pokedex1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/Pokedex1.0.0/ && (cd `dirname .tmp/Pokedex1.0.0` && $(TAR) Pokedex1.0.0.tar Pokedex1.0.0 && $(COMPRESS) Pokedex1.0.0.tar) && $(MOVE) `dirname .tmp/Pokedex1.0.0`/Pokedex1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Pokedex1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_pokedexwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_pokedexwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_pokedexwindow.cpp: mainwindow.h \
		pokedexParser.h \
		pokemon.h \
		evolution.h \
		tm_hm.h \
		level.h \
		pokedexwindow.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) pokedexwindow.h -o moc_pokedexwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

equip.o: equip.cpp equip.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o equip.o equip.cpp

evolution.o: evolution.cpp evolution.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o evolution.o evolution.cpp

level.o: level.cpp level.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o level.o level.cpp

main.o: main.cpp pokedexParser.h \
		pokemon.h \
		evolution.h \
		tm_hm.h \
		level.h \
		pokedexwindow.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

pokedexParser.o: pokedexParser.cpp pokedexParser.h \
		pokemon.h \
		evolution.h \
		tm_hm.h \
		level.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pokedexParser.o pokedexParser.cpp

pokedexwindow.o: pokedexwindow.cpp pokedexwindow.h \
		mainwindow.h \
		pokedexParser.h \
		pokemon.h \
		evolution.h \
		tm_hm.h \
		level.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pokedexwindow.o pokedexwindow.cpp

pokemon.o: pokemon.cpp pokemon.h \
		evolution.h \
		tm_hm.h \
		level.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pokemon.o pokemon.cpp

tm_hm.o: tm_hm.cpp tm_hm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tm_hm.o tm_hm.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_pokedexwindow.o: moc_pokedexwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pokedexwindow.o moc_pokedexwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

